Db backup output improvements
Varying-Vagrant-Vagrants/VVV pull request #2256
Opened 2020-10-11 02:17 UTC by tomjn

- counts the number of databases and shows progress
 - refactored how database names are collected and skipped
 - aligned database names

<img width="764" alt="Screenshot 2020-10-11 at 03 16 14" src="https://user-images.githubusercontent.com/58855/95668758-26323780-0b70-11eb-9a56-0733b17a1a62.png">

## Checks

* [x] I've updated the changelog.
* [x] I've tested this PR
* [x] This PR is for the `develop` branch not the `stable` branch.
* [x] This PR is complete and ready for review.

2020-10-11 14:38 UTC, Mte90 commented
The error reported it is from wp-cli and require a bit of investigation.

2020-10-12 14:31 UTC, msaggiorato commented
Check failure before was some network issue. Re run the check and it run ok. No issues here.

2020-10-12 14:43 UTC, Mte90 requested changes

2020-10-12 14:43 UTC, Mte90 commented on CHANGELOG.md
> +* Enhanced database backup terminal output
Missing the pr number

2020-10-12 14:59 UTC, Mte90 approved these changes

2020-10-12 14:59 UTC, merged